Specify actually supported Rubocop versions
Any version older than this fails tests with this message:

Failures:

  1) RuboCop::Git::Runner exits with violations
     Failure/Error:
       expect { RuboCop::Git::Runner.new.run(options) }
         .to output(%r{Layout/TrailingWhitespace}).to_stdout
         .and raise_error(SystemExit)

          expected block to output /Layout\/TrailingWhitespace/ to stdout, but output nothing

       ...and:

          expected SystemExit, got #<NoMethodError: undefined method `config=' for an instance of RuboCop::AST::ProcessedSource> with backtrace:
            # ./lib/rubocop/git/style_guide.rb:57:in `process_source'
            # ./lib/rubocop/git/style_guide.rb:13:in `violations'
            # ./lib/rubocop/git/style_checker.rb:29:in `offenses'
            # ./lib/rubocop/git/style_checker.rb:17:in `block in violations'
            # ./lib/rubocop/git/style_checker.rb:14:in `map'
            # ./lib/rubocop/git/style_checker.rb:14:in `violations'
            # ./lib/rubocop/git/runner.rb:27:in `violations'
            # ./lib/rubocop/git/runner.rb:67:in `display_violations'
            # ./lib/rubocop/git/runner.rb:17:in `run'
            # ./spec/rubocop/git/runner_spec.rb:5:in `block (3 levels) in <top (required)>'
            # ./spec/rubocop/git/runner_spec.rb:5:in `block (2 levels) in <top (required)>'
       Diff for (output /Layout\/TrailingWhitespace/ to stdout):
       @@ -1 +1 @@
       -/Layout\/TrailingWhitespace/
       +""

     # ./spec/rubocop/git/runner_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) RuboCop::Git::Runner enables cops passed via --only flag
     Failure/Error: source.config = config

     NoMethodError:
       undefined method `config=' for an instance of RuboCop::AST::ProcessedSource
     # ./lib/rubocop/git/style_guide.rb:57:in `process_source'
     # ./lib/rubocop/git/style_guide.rb:13:in `violations'
     # ./lib/rubocop/git/style_checker.rb:29:in `offenses'
     # ./lib/rubocop/git/style_checker.rb:17:in `block in violations'
     # ./lib/rubocop/git/style_checker.rb:14:in `map'
     # ./lib/rubocop/git/style_checker.rb:14:in `violations'
     # ./lib/rubocop/git/runner.rb:27:in `violations'
     # ./lib/rubocop/git/runner.rb:67:in `display_violations'
     # ./lib/rubocop/git/runner.rb:17:in `run'
     # ./spec/rubocop/git/runner_spec.rb:15:in `block (3 levels) in <top (required)>'
     # ./spec/rubocop/git/runner_spec.rb:47:in `capture_stdout'
     # ./spec/rubocop/git/runner_spec.rb:14:in `block (2 levels) in <top (required)>'

1.38.0 was released more than two years ago and the upgrade path from 1.0.0 should be easy since
there is no major version in between, so I don't think it's worth to actually investigate and fix it.